### ISSUE TITLE
LibreOffice not recognising Dracula colour palette

### ISSUE THREAD

**Issue by LiamillionSS** [dracula/libreoffice#10]
Followed instructions on https://draculatheme.com/libreoffice for Windows with adding the .soc file to the palettes folder but the option does not appear as an option as pictured in either image.

Cannot be located in color scheme or color settings

The only relevant link I've found is https://github.com/dracula/libreoffice/issues/3 but I dont understand if the original question was resolved or not, and how that relates to the pictures on the website

Thanks

**Comment by eleanor-clifford** [comment]
#3 was a misunderstanding about palettes vs application colors, which is different from your problem. I don't use Windows so I'm afraid I can't be much help debugging, but other people seem to have had success on Windows before.

**Comment by rjjiii** [comment]
Hello,

Palettes are document-specific color schemes that will only apply to the page area where the document appears. To use the Dracula palette or another palette for a document go to:

**Main Menu > Format > Page Style (Alt + Shift + P) >> Color > Palette**

The theming options do not apply to Windows though. I tried to run a dark interface in Libre Office and it worked great on Linux but on Windows you can make _most_ things dark. This becomes a problem because the remaining bright sections will either be distracting or make your bright (dark mode) icons not visible. 

Perhaps the documentation should have a brief (less than a sentence) mention of how to change the palette with a link to Libre Office's documentation:

https://wiki.documentfoundation.org/Videos/Create_color_palette
