### ISSUE TITLE
Dracula doesn't show up in Application Colors

### ISSUE THREAD

**Issue by reeucq-old** [dracula/libreoffice#3]
copied the .soc file into "~/.config/libreoffice/*/user/config/" on ubuntu 20.04 LTS but the theme just won't show up in libreoffice > options > application colors. any fixes?

**Comment by pandjipras** [comment]
same in Manjaro with libreoffice-fresh.

**Comment by eleanor-clifford** [comment]
ah, this theme is actually just a color palette for making documents with, so it won't appear there. I'll take a look into adding some application colors.

**Comment by eleanor-clifford** [comment]
Application colors have now been added :grin:. I haven't been able to test the script on macOS, but I think it should work (please let me know either way!)

**Comment by computeristic** [comment]
Hi @tim-clifford! Firstly, thank you for adding application colors. On macOS `realpath` does not exist natively. After I installed it (coreutils via homebrew), running it returns `No such file or directory` because of the whitespace between Application and Support in the path and because of the asterisk; I solved it by putting the entire path between double quotation marks and replacing the asterisk with 4. I then received more errors which I later solved by putting `$fname` between double quotation marks in lines 14,16, and 19. Finally, running it after all these modifications returns:

> cp: /Users/***/Library/Application Support/LibreOffice/4/user/config is a directory (not copied).
Settings file doesn't exist in expected location, aborting...

I'm not a programmer but I can test any changes to the script on my mac and report back to you. I'm on macOS 10.14.6 (Mojave).

**Comment by eleanor-clifford** [comment]
Hi @computeristic! Thanks for being so thorough. I've uploaded a new version to the `macos` branch (download [here](https://github.com/dracula/libreoffice/archive/refs/heads/macos.zip) in case you're not too familiar with git). Let me know if it works!

**Comment by computeristic** [comment]
Thank you for your prompt reply and changes, I appreciate it! First time I ran it I got `head: illegal line count -- -1` and then running it again (with no changes made) returns `Settings file doesn't match expected format, aborting...` every time. This cleared the file registrymodifications.xcu.

**Comment by computeristic** [comment]
Manually copying the contents of dracula.xcu into registrymodifications.xcu (after the 2nd line) worked. This is an easy workaround for the timebeing.

**Comment by eleanor-clifford** [comment]
Ah I see, macOS has a different version of `head` which doesn't support what the script was originally doing. I've fixed that bit now in 802d0d4, can you give it a try?

**Comment by computeristic** [comment]
Yes, it works now! Thanks again!
